# Generated by Django 4.1.7 on 2023-04-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category_project_client_project_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('brl', 'BRL'), ('btc', 'BTC')], max_length=15),
        ),
    ]
