# Generated by Django 4.1.7 on 2023-04-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
