# Generated by Django 4.1.7 on 2023-04-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.currency'),
        ),
    ]
