# Generated by Django 4.1.7 on 2023-04-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='skills',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.skill'),
        ),
    ]
