# Generated by Django 4.1.7 on 2023-04-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projects_options_projects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Full description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Short description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
