# Generated by Django 4.1.7 on 2023-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projects_full description_projects_short description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Full description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
