# Generated by Django 4.1.7 on 2023-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Full description',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Short description',
        ),
        migrations.AddField(
            model_name='projects',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Full description'),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Short description'),
        ),
    ]
