# Generated by Django 4.1.7 on 2023-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_projects_full description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date_posted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
