# Generated by Django 4.1.7 on 2023-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projects_date_posted_projects_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='budget',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
