# Generated by Django 4.1.7 on 2023-04-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projects_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='currency',
            field=models.CharField(choices=[('btc', 'BTC')], default='BTC', max_length=5),
        ),
    ]
