# Generated by Django 4.1.7 on 2023-04-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
