# Generated by Django 4.1.7 on 2023-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_freelancer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
