# Generated by Django 4.1.7 on 2023-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_wallets_options_alter_wallets_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallets',
            old_name='public_key',
            new_name='address',
        ),
        migrations.AddField(
            model_name='wallets',
            name='public_key_hex',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
