# Generated by Django 4.1.7 on 2023-04-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_public_key_wallets_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='private_key_wif',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
